### ISSUE TITLE
when using the detailTemplate, there is an error on querySelector and the detailtemplate is broken

### ISSUE THREAD

**Issue by gerhardboer** [syncfusion/ej2-grids#17] opened 2019-09-27 11:56 UTC
Stackblitz: https://stackblitz.com/edit/angular-5bgdss

It is from an Angular context, but i've located the issue in grid.js

When the grid is rendered, and there is a detailTemplate, it tries to set the widths on the columns in the header. However, the header is not yet created, which leads to the "undefined" error;
ERROR
Error: Cannot read property 'querySelector' of undefined
width-controller.js:114

**Comment by thavasianand** [comment] 2019-09-30 11:37
Hi gerhardboer, 

We are able to reproduce the reported issue “DetailTemplate is not working while the columns are auto generated” from our end. We have confirmed the issue is a defect and logged a defect report. The fix for this issue is estimated to be available in any of our upcoming release.

Regards,
Thavasianand S.

**Comment by pavithra95subramaniam** [comment] 2019-10-16 10:40
Hi @gerhardboer ,

Thanks for your patience.

We are glad to announce that our patch release ([v17.3.17](https://www.npmjs.com/~syncfusionorg))has been rolled out successfully and in that release, we have included  “**DetailTemplate is not working while the columns are auto generated**” fix.

Regards,
Pavithra S.

**Comment by rajendranr-5483** [comment] 2021-07-20 06:46
We are closing this thread now since there is no recent activity. Please feel free to reopen the issue if you have any comments for the reinvestigation.

**Closed by rajendranr-5483** 2021-07-20 06:46 UTC
